version: 2
updates:
- package-ecosystem: pip
  directories:
    - "/"
    - "/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  labels:
  - dependencies
- package-ecosystem: Docker
  directories:
    - "/"
    - "/docker"
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: yarn
  directory: "/"
  schedule:
    interval: daily
  labels:
  - dependencies
