# Generated by Django 3.1.13 on 2022-01-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seta', '0001_squashed_0002_remove_task_request_and_jp_timeout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPriority',
        ),
    ]
